name: Test
run-name: ${{ github.actor }} is learning GitHub Actions
on: [ push ]
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      selenoid:
        image: aerokube/selenoid:latest-release
        options: >-
          --name selenoid
          --network host
          --privileged
        ports:
          - 4444:4444
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Run tests with Gradle
        env:
          SELENOID_URL: http://localhost:4444/wd/hub
        run: ./gradlew clean test
