name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Get selenoid
        uses: Xotabu4/selenoid-github-action@v2

      - name: Run tests with Gradle
        run: ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub

      - name: Download history report
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history

      - name: Send report
        uses: peaceiris/actions-gh-pages@v2
        if: always()
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history