name: Test
on: [ push ]

jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      selenoid:
        image: aerokube/selenoid:latest-release
        ports:
          - 4444:4444
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '18'

      - name: Run tests with Gradle
        env:
          SELENOID_URL: http://localhost:4444/wd/hub
        run: ./gradlew test --warning-mode all

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/test